// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "BitMatchTransferWorker",
    platforms: [.macOS(.v15)],
    products: [
        .library(name: "BitMatchTransferCore", targets: ["BitMatchTransferCore"]),
        .executable(name: "bitmatch-transfer-worker", targets: ["BitMatchTransferWorker"]),
    ],
    targets: [
        .target(
            name: "BitMatchTransferCore",
            path: "Shared",
            exclude: [
                "Core/Extensions",
                "Core/ViewModels",
                "Views",
                "Core/Models/AdaptiveNavigationPresentation.swift",
                "Core/Models/CompletionVerdictPresentation.swift",
                "Core/Models/NotificationPermissionPolicy.swift",
                "Core/Models/PhotographerJobModels.swift",
                "Core/Models/PhotographerJobPresentation.swift",
                "Core/Models/RemoteBackupModels.swift",
                "Core/Models/ReportSummary.swift",
                "Core/Models/ResultPresentation.swift",
                "Core/Models/SharedModels.swift",
                "Core/Models/TransferModels.swift",
                "Core/Models/TransferOperationPresentation.swift",
                "Core/Models/TransferPlanPresentation.swift",
                "Core/Models/TransferWorkflowPresentation.swift",
                "Core/Services/Camera",
                "Core/Services/ASCMHLGenerator.swift",
                "Core/Services/CameraMemoryService.swift",
                "Core/Services/CameraNamingService.swift",
                "Core/Services/CameraStructureDetector.swift",
                "Core/Services/ComparisonCoordinator.swift",
                "Core/Services/CopyVerifyExecutor.swift",
                "Core/Services/ErrorReportingService.swift",
                "Core/Services/FolderInfoService.swift",
                "Core/Services/FolderRecipeRenderer.swift",
                "Core/Services/IOSBackgroundTaskService.swift",
                "Core/Services/LocalTransferJournal.swift",
                "Core/Services/MHLGenerator.swift",
                "Core/Services/OperationStateMachine.swift",
                "Core/Services/OperationStateManager.swift",
                "Core/Services/OperationStateService.swift",
                "Core/Services/OperationTimingService.swift",
                "Core/Services/PhotographerCardAnalyzer.swift",
                "Core/Services/PhotographerDestinationResolver.swift",
                "Core/Services/ProjectRemoteCoordinator.swift",
                "Core/Services/ProjectStoreProtocol.swift",
                "Core/Services/RemoteBackupCoordinator.swift",
                "Core/Services/RemoteBackupProvider.swift",
                "Core/Services/RemoteBackupQueue.swift",
                "Core/Services/ReportCoordinator.swift",
                "Core/Services/ReportExporter.swift",
                "Core/Services/ResultsOverflowService.swift",
                "Core/Services/SharedAppCoordinator.swift",
                "Core/Services/SharedCameraDetectionService.swift",
                "Core/Services/SharedReportGenerationService.swift",
                "Core/Services/UserDefaultsPhotographerJobStore.swift",
            ],
            sources: [
                "Core/Models/CameraModels.swift",
                "Core/Models/OperationModels.swift",
                "Core/Models/TransferPrimitives.swift",
                "Core/Services/AsyncSemaphore.swift",
                "Core/Services/ChecksumCache.swift",
                "Core/Services/File/FileCopyService.swift",
                "Core/Services/File/FileTreeEnumerator.swift",
                "Core/Services/File/SafetyValidator.swift",
                "Core/Services/Logging/SharedLogger.swift",
                "Core/Services/ServiceProtocols.swift",
                "Core/Services/SharedChecksumService.swift",
                "Core/Services/SharedFileOperationsService.swift",
                "Core/Worker/TransferWorkerProtocol.swift",
                "Core/Worker/TransferWorkerRuntime.swift",
            ],
            swiftSettings: [.swiftLanguageMode(.v5)]
        ),
        .executableTarget(
            name: "BitMatchTransferWorker",
            dependencies: ["BitMatchTransferCore"],
            path: "WorkerCLI",
            swiftSettings: [.swiftLanguageMode(.v5)]
        ),
        .testTarget(
            name: "BitMatchTransferWorkerTests",
            dependencies: ["BitMatchTransferCore"],
            path: "WorkerTests",
            resources: [.copy("Fixtures")],
            swiftSettings: [.swiftLanguageMode(.v5)]
        ),
    ]
)
